//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class @return {
    
    private returnDataResponse dataResponseField;
    
    /// <remarks/>
    public returnDataResponse dataResponse {
        get {
            return this.dataResponseField;
        }
        set {
            this.dataResponseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class returnDataResponse {
    
    private returnDataResponseLinkConditions linkConditionsField;
    
    /// <remarks/>
    public returnDataResponseLinkConditions linkConditions {
        get {
            return this.linkConditionsField;
        }
        set {
            this.linkConditionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class returnDataResponseLinkConditions {
    
    private returnDataResponseLinkConditionsLinkCondition[] linkConditionField;
    
    private string linkSetIDField;
    
    private string msgTypeField;
    
    private float schemaVersionField;
    
    private bool schemaVersionFieldSpecified;
    
    private string sourceSetIDField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    private string unitsField;
    
    private sbyte statusIdField;
    
    private bool statusIdFieldSpecified;
    
    private string statusTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("linkCondition")]
    public returnDataResponseLinkConditionsLinkCondition[] linkCondition {
        get {
            return this.linkConditionField;
        }
        set {
            this.linkConditionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinkSetID {
        get {
            return this.linkSetIDField;
        }
        set {
            this.linkSetIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MsgType {
        get {
            return this.msgTypeField;
        }
        set {
            this.msgTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SchemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SchemaVersionSpecified {
        get {
            return this.schemaVersionFieldSpecified;
        }
        set {
            this.schemaVersionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceSetID {
        get {
            return this.sourceSetIDField;
        }
        set {
            this.sourceSetIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TimestampSpecified {
        get {
            return this.timestampFieldSpecified;
        }
        set {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte StatusId {
        get {
            return this.statusIdField;
        }
        set {
            this.statusIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusIdSpecified {
        get {
            return this.statusIdFieldSpecified;
        }
        set {
            this.statusIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StatusText {
        get {
            return this.statusTextField;
        }
        set {
            this.statusTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class returnDataResponseLinkConditionsLinkCondition {
    
    private int idField;
    
    private string dataTypeField;
    
    private short speedField;
    
    private short travelTimeField;
    
    private float travelTimeFloatField;
    
    private System.DateTime asOfField;
    
    private bool asOfFieldSpecified;
    
    /// <remarks/>
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string DataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    public short Speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    public short TravelTime {
        get {
            return this.travelTimeField;
        }
        set {
            this.travelTimeField = value;
        }
    }
    
    /// <remarks/>
    public float TravelTimeFloat {
        get {
            return this.travelTimeFloatField;
        }
        set {
            this.travelTimeFloatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime asOf {
        get {
            return this.asOfField;
        }
        set {
            this.asOfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool asOfSpecified {
        get {
            return this.asOfFieldSpecified;
        }
        set {
            this.asOfFieldSpecified = value;
        }
    }
}
